eh: Add alloc/free for dependent exception
Recent gcc require dependent exceptions.
abi/libsupc/eh_ptr.o: In function
`std::rethrow_exception(std::__exception_ptr::exception_ptr)':
(.text._ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE+0x21):
undefined reference to `__cxa_allocate_dependent_exception'
abi/libsupc/eh_ptr.o: In function
`__gxx_dependent_exception_cleanup(_Unwind_Reason_Code,
_Unwind_Exception*)':
(.text._ZL33__gxx_dependent_exception_cleanup19_Unwind_Reason_CodeP17_Unwind_Exception+0x30):
undefined reference to `__cxa_free_dependent_exception'

Signed-off-by: Bernhard Reutner-Fischer <rep.dot.nop@gmail.com>